# Generated by Django 3.2.5 on 2021-07-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
