# Generated by Django 3.2.5 on 2021-07-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='check',
            new_name='show',
        ),
    ]
